version: '3.8'

services:
  client:
    container_name: lckyn-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7100:7100"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  server:
    container_name: lckyn-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7101:7101"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/lckyn-chat
    depends_on:
      - mongodb

  mongodb:
    container_name: lckyn-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  default:
    name: lckyn-network

volumes:
  mongodb_data:
